### vscode の rest-client 用リクエストファイル

GET http://localhost:5000/movies

###

GET http://localhost:5000/movies/5f7818c7f1ae7349e2ff9009

###

POST http://localhost:5000/movies
content-type: application/json

{
    "name": "The Dark Knight",
    "casts": ["Christian Bale", "Heath Ledger", "Aaron Eckhart", "Michael Caine"],
    "genres": ["Action", "Crime", "Drama"]
}

###

PUT http://localhost:5000/movies/5f7818dff1ae7349e2ff900c
content-type: application/json

{
    "name": "The Dark Knightttttt",
    "casts": ["Christian Bale", "Heath Ledger", "Aaron Eckhart", "Michael Caine"],
    "genres": ["Action", "Crime", "Drama"]
}

###

DELETE http://localhost:5000/movies/5f7818c7f1ae7349e2ff9009
